
close all
clear

d = struct();


startDate = mm(2003,01);

% Stock lending rates

rates = readmatrix( ...
    "raw-data/ie_table_b-1-2_retail_interest_rates_-_loans_outstanding_amounts.xls" ...
    , "sheet", 2 ...
    , "range", "C12:M246" ...
);

volumes = readmatrix( ...
    "raw-data/ie_table_b-1-2_retail_interest_rates_-_loans_outstanding_amounts.xls" ...
    , "sheet", 3 ...
    , "range", "C12:M246" ...
);

d.rl_m = Series(startDate, sum(rates .* volumes, 2) ./ sum(volumes, 2));
d.rl = convert(d.rl_m, Frequency.QUARTERLY);


% Stock deposit rates

rates = readmatrix( ...
    "raw-data/ie_table_b-1-1_retail_interest_rates_-_deposits_outstanding_amounts.xls" ...
    , "sheet", 2 ...
    , "range", "C12:I246" ...
);

volumes = readmatrix( ...
    "raw-data/ie_table_b-1-1_retail_interest_rates_-_deposits_outstanding_amounts.xls" ...
    , "sheet", 3 ...
    , "range", "C12:I246" ...
);

d.rd_m = Series(startDate, sum(rates .* volumes, 2) ./ sum(volumes, 2));
d.rd = convert(d.rd_m, Frequency.QUARTERLY);


% New lending and deposit rates

rates = readmatrix( ...
    "raw-data/ie_table_b-2-1_retail_interest_rates_and_volumes_-_loans_and_deposits_new.xlsx" ...
    , "sheet", 2 ...
    , "range", "C13:T247" ...
);

volumes = readmatrix( ...
    "raw-data/ie_table_b-2-1_retail_interest_rates_and_volumes_-_loans_and_deposits_new.xlsx" ...
    , "sheet", 3 ...
    , "range", "C13:R247" ...
);

posR = setdiff(1:16, [7, 11]);
posV = 1:14;
d.new_rl_m = Series(startDate, sum(rates(:,posR) .* volumes(:, posV), 2) ./ sum(volumes(:, posV), 2));
d.new_rl = convert(d.new_rl_m, Frequency.QUARTERLY);

posV = 15:16;
posR = 17:18;
d.new_rd_m = Series(startDate, sum(rates(:,posR) .* volumes(:, posV), 2) ./ sum(volumes(:, posV), 2));
d.new_rd = convert(d.new_rd_m, Frequency.QUARTERLY);


% Loans to private sector

assets = readmatrix( ...
    "raw-data/ie_table_a-4-1_credit_institutions_(domestic_market_group)_-_aggregate_balance_sheet.xls" ...
    , "sheet", 2 ...
    , "range", "C12:R245" ...
);

liabs = readmatrix( ...
    "raw-data/ie_table_a-4-1_credit_institutions_(domestic_market_group)_-_aggregate_balance_sheet.xls" ...
    , "sheet", 3 ...
    , "range", "C12:O245" ...
);

d.ta_m = Series(startDate, assets(:, 1));
d.le_m = Series(startDate, sum(assets(:, [4, 5, 10, 11]), 2));
d.bk_m = Series(startDate, liabs(:, 10));

d.sec_m = Series(startDate, sum(assets(:, [8, 9, 12, 13]), 2));

d.ta = convert(d.ta_m, Frequency.QUARTERLY);
d.le = convert(d.le_m, Frequency.QUARTERLY);
d.sec = convert(d.sec_m, Frequency.QUARTERLY);
d.bk = convert(d.bk_m, Frequency.QUARTERLY);

databank.toSheet(d, "input-data/banking.csv", numDividers=2);

